/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on 2011/3/12, 上午 04:37:48
 */

package gui;

import testclient.*;
import javax.swing.*;

/**
 *
 * @author YTC
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        ApplyA = new javax.swing.JTextField();
        Apply = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ApplyP = new javax.swing.JPasswordField();
        ConfirmP = new javax.swing.JPasswordField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Apply.setText("送出");
        Apply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplyMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 18));
        jLabel1.setText("輸入帳號:");

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 18));
        jLabel2.setText("輸入密碼:");

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 18));
        jLabel3.setText("再次輸入密碼:");

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 18));
        jLabel4.setText("註冊新帳號");

        Cancel.setText("取消");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApplyA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApplyP, 0, 0, Short.MAX_VALUE)
                            .addComponent(ConfirmP, 0, 0, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Apply)
                .addGap(59, 59, 59)
                .addComponent(Cancel)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ApplyA, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ApplyP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ConfirmP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apply)
                    .addComponent(Cancel))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyMouseClicked
        boolean a = false;
        boolean p = false;
        String check1 = new String(ApplyP.getPassword());
        String check2 = new String(ConfirmP.getPassword());
                
        if( ApplyA.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "請輸入帳號", "", JOptionPane.ERROR_MESSAGE);
        } else if( ApplyA.getText().contains(" ") ) {
            JOptionPane.showMessageDialog(this, "帳號請不要有空白", "", JOptionPane.ERROR_MESSAGE);
            ApplyA.setText("");
        } else {
            ApplyAccount  = ApplyA.getText();
            a = true;
        }

        if(check1.equals("") ) {
            JOptionPane.showMessageDialog(this, "請輸入密碼", "", JOptionPane.ERROR_MESSAGE);
        } else if( check1.contains(" ") ) {
            JOptionPane.showMessageDialog(this, "密碼請不要有空白", "", JOptionPane.ERROR_MESSAGE);
            ApplyP.setText("");
        } else if (check1.equals(check2)) {
            ApplyPassword = new String(ApplyP.getPassword());
            p = true;
        } else {
            JOptionPane.showMessageDialog(this, "兩次密碼輸入不相同,請再次確認密碼","", JOptionPane.ERROR_MESSAGE);
        }

        if (a ==true && p == true){
             setVisible(false);
             if(NewMain.NWKSER.loginas(ApplyAccount, ApplyPassword, true)){

             }
             else{
                 setVisible(true);
                 JOptionPane.showMessageDialog(this, "連線失敗,請檢察網路線或路由器", "", JOptionPane.ERROR_MESSAGE);
             }
             
        }

    }//GEN-LAST:event_ApplyMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
       setVisible(false);

    }//GEN-LAST:event_CancelMouseClicked

    public void RegisterFailed(){
        setVisible(true);
        JOptionPane.showMessageDialog(this, "帳號已被註冊,請重新輸入","", JOptionPane.ERROR_MESSAGE);
        ApplyA.setText("");
        ApplyP.setText("");
        ConfirmP.setText("");
    }

    public void RegisterSuccess(){
        JOptionPane.showMessageDialog(this, "註冊成功,已登入", "", JOptionPane.PLAIN_MESSAGE);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }




public String ApplyAccount;
public String ApplyPassword;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JTextField ApplyA;
    private javax.swing.JPasswordField ApplyP;
    private javax.swing.JButton Cancel;
    private javax.swing.JPasswordField ConfirmP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables

}
