/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Typefriend.java
 *
 * Created on 2011/3/13, 下午 04:03:41
 */

package gui;

import testclient.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author YTC
 */
public class Typefriend extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public Typefriend() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFriend = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addgroup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addFriend.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        Add.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        Add.setText("新增好友");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        Cancel.setText("取消");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        jLabel1.setText("請輸入帳號:");

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        jLabel2.setText("新增至群組:");

        addgroup.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Add)
                .addGap(67, 67, 67)
                .addComponent(Cancel)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        String addname = new String(addFriend.getText());
        String groupname = new String(addgroup.getText());
        boolean check1 = false;
        boolean check2 = false;       
        if( addname.equals("") ) {
            JOptionPane.showMessageDialog(this, "請輸入帳號", "", JOptionPane.ERROR_MESSAGE);
        } else if( addname.contains(" ") ) {
            JOptionPane.showMessageDialog(this, "帳號請不要有空白", "", JOptionPane.ERROR_MESSAGE);
            addFriend.setText("");
        } else if(addname.equals(NewMain.NWKSER.friendlist.who)){
            JOptionPane.showMessageDialog(this, "你不能新增自己為好友", "", JOptionPane.ERROR_MESSAGE);
            addFriend.setText("");
        }
        else {
            check1 = true;
        }
        
        if( groupname.equals("") ) {
            JOptionPane.showMessageDialog(this, "請輸入群組", "", JOptionPane.ERROR_MESSAGE);
        } else if( groupname.contains(" ") ) {
            JOptionPane.showMessageDialog(this, "群組名稱請不要有空白", "", JOptionPane.ERROR_MESSAGE);
            addgroup.setText("");
        } else {
            check2 = true;
        }

        if(check1==true&&check2==true){
            JOptionPane.showMessageDialog(this, "已送出邀請,請等待對方回覆確認為好友", "", JOptionPane.PLAIN_MESSAGE);
            NewMain.NWKSER.sendmsg("/addfriend "+addname+" "+groupname);
            setVisible(false);
        }
    }//GEN-LAST:event_AddMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        setVisible(false);
    }//GEN-LAST:event_CancelMouseClicked

    public void addFailed(String reason){
        setVisible(true);
        if (reason.equals("notexist")){
            JOptionPane.showMessageDialog(this, "查無此帳號, 請重新輸入", "", JOptionPane.ERROR_MESSAGE);
            addFriend.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "此帳號已在好友名單, 請重新輸入", "", JOptionPane.ERROR_MESSAGE);
            addFriend.setText("");
        }
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Typefriend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField addFriend;
    private javax.swing.JTextField addgroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
